version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config:/mosquitto/config/
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - iot-network

networks:
  iot-network:
    name: iot-network
    driver: bridge
    external: true
