version: '3.8'
services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    environment:
      - INIT_ASSETS=1
    volumes:
      - ./assets/:/www/assets:rw
    ports:
      - 80:8080
    restart: unless-stopped
    networks:
      - iot-network

networks:
  iot-network:
    name: iot-network
    driver: bridge
    external: true